### ISSUE TITLE
v1.5.0 breaks stubbing in rspec 3 hooks (eg around:each)

### ISSUE THREAD

**Issue by onyxraven** [freerange/mocha#329]
Before/around each are considered 'inside' the example in rspec, and previously, stubs could be set inside those hooks.  As far as I know, the mocha plugin has always properly cleaned up these stubs because it attaches to the hooks first, therefore it still cleans up in the after example phase.

In 1.5.0, this now throws

Example:

```ruby
      around(:each) do |ex|
        Chef::Knife::Ssh.any_instance.stubs(:run)
      end
```

Throws: 

```
     Failure/Error: Chef::Knife::Ssh.any_instance.stubs(:run)

     Mocha::NotInitializedError:
       Mocha methods cannot be used outside the context of a test
```

**Comment by floehopper** [comment]
Thanks for reporting this - I'm investigating.

**Comment by floehopper** [comment]
@onyxraven:

This doesn't appear to be a problem when stubbing in an RSpec `before` block. However, RSpec appears to treat `around` blocks differently from `before` blocks. Even when using the default RSpec mocks, a similar exception is raised:

> The use of doubles or partial doubles from rspec-mocks outside of the per-test lifecycle is not supported

```ruby
require 'spec_helper'
require 'foo'

RSpec.describe Foo do
  around do |example|
    allow(Foo).to receive(:foo).and_return('stubbed-foo')
    example.run
  end

  it 'foo' do
    expect(Foo.foo).to eq('stubbed-foo')
  end
end
```

Running this spec generates the following output:

```
$ rspec spec/foo_spec.rb 
F

Failures:

  1) Foo foo
     Failure/Error: allow(Foo).to receive(:foo).and_return('stubbed-foo')
       The use of doubles or partial doubles from rspec-mocks outside of the per-test lifecycle is not supported.
     # ./spec/foo_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 0.02591 seconds (files took 0.09476 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/foo_spec.rb:10 # Foo foo
```

The RSpec behaviour above appears to be intentional - [the `around` hooks documentation][1] says:

> **WARNING**: Mock frameworks are set up and torn down within the context of
running the example. You cannot interact with them directly in around hooks.

There's also some useful discussion in [this RSpec issue][2] including some work-arounds.

The fact that stubbing with Mocha used to work in an `around` block was accidental and prone to problems. The change in Mocha v1.5.0 prevents this in order to avoid those problems and in doing so brings Mocha into line with RSpec mocks. So I don't think it makes sense to revert this change.

Hopefully the above RSpec documentation links will help, but let me know if you get stuck trying to fix your specs to work with Mocha v1.5.0.

[1]: https://relishapp.com/rspec/rspec-core/v/3-5/docs/hooks/around-hooks
[2]: https://github.com/rspec/rspec-core/issues/1598

**Comment by floehopper** [comment]
@onyxraven I'm going to assume this is resolved and am closing the issue, but feel free to get back to me if you have further questions.

**Comment by onyxraven** [comment]
Thanks for the really informational response. Hopefully others which stumble across this change will find this PR.  

I can't find any cases where we are using an 'around' for this that can't be moved to a 'before' for any reason, so it is a straight forward change.

**Comment by floehopper** [comment]
Cool 👍

**Comment by VictorYou** [comment]
'before' hook is not working for me, eg: code as below still fails with the same error message
Failure/Error: @name.expects(:size).returns 100
     
     Mocha::NotInitializedError:
       Mocha methods cannot be used outside the context of a test


require 'mocha/test_unit'

RSpec.describe "test" do
  before(:each) do
    @name = 'viyou'
    @name.expects(:size).returns 100 
  end 

  describe "test" do
    it "test" do
      expect(@name).to eq 'viyou'
      expect(@name.size).to eq 100
    end
  end
end

can you please suggest what to do? thanks.

**Comment by floehopper** [comment]
@VictorYou 

I've tried reproducing this in [this standalone gist](https://gist.github.com/floehopper/31c109be5fddd5e3a76fa9d3165268ff), but I don't see any test failures/errors. The only difference I can see is that I'm not requiring "mocha/test_unit" - [the instructions in the README](https://github.com/freerange/mocha#rspec) explain that you don't need to require "mocha" explicitly when using RSpec, and I don't understand why you'd need the integration with Test::Unit anyway.

Do you have the `config.mock_with :mocha` in your RSpec config? Are you sure your expect is a `before(:each)` and not a `before(:all)`? I would expect the latter to give the error you are seeing. 

Please can you try to fork & modify my gist to try to reproduce the problem you are seeing? I'm on holiday at the moment, so it might be a while before I can respond to any further questions.

**Comment by VictorYou** [comment]
@floehopper 
thanks for your guide. i did miss config.mock_with :mocha. after adding it, this issue is gone.
the error message will appear with before(:all), not before(:each) as you said.
